# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2225f69bbc43ca5b1ba2d8a5fea81f3f63556ccb5369a3a289b7d870e627ba79a1204e71b12b4bf2ffbe665628b16b3d56ad9ceac183be36ef0e27398af66f11

test:
  secret_key_base: ff3cc9af39a1296f8c3f1fbd5796bc3c3c3ca54dacdf5930b964e6a4019b90416220ff53365d4225c5f44e52846b45ac9fafd8bd6ae684e8f82cc92e1ef4d9be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
